### ISSUE TITLE
Question: onFlush vs preFlush

### ISSUE THREAD

**Issue by martinssipenko** [agluh/outbox-bundle#1]
Hi, 

I've been reading through your code and have noticed that you subscribe your [`PersistDomainEventsListener` to Doctrines `onFlush` event](https://github.com/agluh/outbox-bundle/blob/737d5b95727b3e5c7af09cd788b5866b3daa56c8/src/Doctrine/EventListener/PersistDomainEventsListener.php#L41). I'm not saying there is anything wrong with it just trying to understand why exactly `onFlush` event is used instead of `preFlush`? When running code locally I discovered that using `preFlush` removed the need to `computeChangeSet()` in [`DoctrineOutboxEventRepository` line 27](https://github.com/agluh/outbox-bundle/blob/737d5b95727b3e5c7af09cd788b5866b3daa56c8/src/Doctrine/DoctrineOutboxEventRepository.php#L27-L28). Perhaps you could point out to me why is it like this?

**Comment by agluh** [comment]
Hi, thanks for your question.

As far as I know, preFlush event occurs before UnitOfWork does computation of any changes in managed entities. I am expecting problems with `$uow->getScheduledEntityUpdates()` if it will be called before those computations. Basically it should return empty array in that case. So we will lose domain events from updated entities.

I've seen a lot of examples of event listeners and almost all of them relies on onFlush event when a new entity needs to be attached to the UOW during flushing.

Anyway you are free to test your idea (especially with entity updates) and tell us if it works :)
